import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { verifyToken } from "@/lib/auth";
import { getAIConfig } from "@/lib/ai";
import { buildQuizGeneratePrompt, parseQuestionsFromAIResponse } from "@/lib/prompts/quiz";

export async function POST(req: NextRequest) {
  try {
    const token = req.headers.get("authorization")?.replace("Bearer ", "");
    if (!token) return new Response("未登录", { status: 401 });
    const payload = await verifyToken(token);
    if (!payload) return new Response("登录已过期", { status: 401 });

    const { subProjectId, title, description, autoGenerate, quizDesignTemplateContent, analysisPrompt, passScore } = await req.json();
    if (!subProjectId || !title) {
      return new Response("缺少必填字段", { status: 400 });
    }

    // 验证 subProject 归属当前教师
    const subProject = await prisma.subProject.findFirst({
      where: { id: subProjectId, task: { teacherId: String(payload.userId) } },
      include: {
        task: { include: { User: { select: { name: true } } } },
        QuizActivity: { where: { status: "ACTIVE" } },
      },
    });
    if (!subProject) {
      return new Response("子项目不存在或无权访问", { status: 404 });
    }

    const task = subProject.task;

    // 如果传了 quizDesignTemplateContent 且 autoGenerate 为 true，使用它生成题目
    if (quizDesignTemplateContent && autoGenerate) {
      let knowledgeBases: Array<{ name: string; content: string }> = [];
      if (task.knowledgeBaseIds) {
        try {
          const kbIds = JSON.parse(task.knowledgeBaseIds) as string[];
          if (kbIds.length > 0) {
            const kbs = await prisma.knowledgeBase.findMany({
              where: { id: { in: kbIds }, teacherId: task.teacherId },
            });
            knowledgeBases = kbs.map((kb) => ({ name: kb.name, content: kb.content }));
          }
        } catch { /* ignore */ }
      }

      const prompt = buildQuizGeneratePrompt(quizDesignTemplateContent, {
        task: {
          title: task.title,
          grade: task.grade,
          subject: task.subject,
          objectives: task.objectives,
          knowledgeBase: task.knowledgeBase,
        },
        presetConv: { description: description || null },
        knowledgeBases,
        teacherName: task.User.name,
        quizCount: 5,
        convDescription: description || "",
        kbList: knowledgeBases && knowledgeBases.length > 0
          ? knowledgeBases.map((kb) => `【${kb.name}】：\n${kb.content}`).join("\n\n")
          : "",
      });

      try {
        const aiConfig = await getAIConfig();
        const aiResponse = await fetch(`${aiConfig.baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${aiConfig.apiKey}`,
          },
          body: JSON.stringify({
            model: aiConfig.model,
            messages: [{ role: "user", content: prompt }],
            max_tokens: 4000,
          }),
        });

        if (aiResponse.ok) {
          const aiData = await aiResponse.json();
          const rawContent = aiData.choices?.[0]?.message?.content || "";
          const parsed = parseQuestionsFromAIResponse(rawContent);

          const quiz = await prisma.quizActivity.create({
            data: {
              subProjectId,
              title,
              description: description || null,
              passScore: passScore || 60,
              status: "INACTIVE",
              analysisPrompt: analysisPrompt || null,
              updatedAt: new Date(),
              Question: {
                create: parsed.map((q, idx) => ({
                  type: q.type || "SINGLE_CHOICE",
                  content: q.content,
                  options: typeof q.options === "string" ? q.options : JSON.stringify(q.options || {}),
                  answer: q.answer,
                  difficulty: q.difficulty || "BASIC",
                  explanation: q.explanation || null,
                  order: idx,
                })),
              },
            },
            include: { Question: { orderBy: { order: "asc" } } },
          });
          const { Question: Q1, ...quizData1 } = quiz;
          return NextResponse.json({ ...quizData1, questions: Q1, autoGenerated: true, count: parsed.length }, { status: 201 });
        }
      } catch (e) {
        console.error("AI自动生成失败:", e);
      }
      // AI失败时仍创建空作业
      const quiz = await prisma.quizActivity.create({
        data: { subProjectId, title, description: description || null, passScore: passScore || 60, status: "INACTIVE", updatedAt: new Date() },
        include: { Question: { orderBy: { order: "asc" } } },
      });
      return NextResponse.json({ ...quiz, autoGenerated: false, count: 0 }, { status: 201 });
    }

    // 查找该教师名下的默认作业设计模板
    const defaultTemplate = await prisma.analysisTemplate.findFirst({
      where: { teacherId: String(payload.userId), type: "QUIZ_DESIGN", isDefault: true },
    });

    // 如果请求自动生成且有模板
    if (autoGenerate && defaultTemplate) {
      // 解析引用的知识库
      let knowledgeBases: Array<{ name: string; content: string }> = [];
      if (task.knowledgeBaseIds) {
        try {
          const kbIds = JSON.parse(task.knowledgeBaseIds) as string[];
          if (kbIds.length > 0) {
            const kbs = await prisma.knowledgeBase.findMany({
              where: { id: { in: kbIds }, teacherId: task.teacherId },
            });
            knowledgeBases = kbs.map((kb) => ({ name: kb.name, content: kb.content }));
          }
        } catch { /* ignore */ }
      }

      const prompt = buildQuizGeneratePrompt(defaultTemplate.content, {
        task: {
          title: task.title,
          grade: task.grade,
          subject: task.subject,
          objectives: task.objectives,
          knowledgeBase: task.knowledgeBase,
        },
        presetConv: { description: description || null },
        knowledgeBases,
        teacherName: task.User.name,
        quizCount: 5,
        convDescription: description || "",
        kbList: knowledgeBases && knowledgeBases.length > 0
          ? knowledgeBases.map((kb) => `【${kb.name}】：\n${kb.content}`).join("\n\n")
          : "",
      });

      try {
        const aiConfig = await getAIConfig();
        const aiResponse = await fetch(`${aiConfig.baseURL}/chat/completions`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${aiConfig.apiKey}`,
          },
          body: JSON.stringify({
            model: aiConfig.model,
            messages: [{ role: "user", content: prompt }],
            max_tokens: 4000,
          }),
        });

        if (aiResponse.ok) {
          const aiData = await aiResponse.json();
          const rawContent = aiData.choices?.[0]?.message?.content || "";
          const parsed = parseQuestionsFromAIResponse(rawContent);

          // 创建作业 + 题目原子事务
          const quiz = await prisma.quizActivity.create({
            data: {
              subProjectId,
              title,
              description: description || null,
              quizDesignTemplateId: defaultTemplate.id,
              passScore: passScore || 60,
              status: "INACTIVE",
              analysisPrompt: analysisPrompt || null,
              updatedAt: new Date(),
              Question: {
                create: parsed.map((q, idx) => ({
                  type: q.type || "SINGLE_CHOICE",
                  content: q.content,
                  options: typeof q.options === "string" ? q.options : JSON.stringify(q.options || {}),
                  answer: q.answer,
                  difficulty: q.difficulty || "BASIC",
                  explanation: q.explanation || null,
                  order: idx,
                })),
              },
            },
              include: { Question: { orderBy: { order: "asc" } } },
          });
          const { Question: Q3, ...quizData3 } = quiz;
          return NextResponse.json({ ...quizData3, questions: Q3, autoGenerated: true, count: parsed.length }, { status: 201 });
        }
      } catch (e) {
        console.error("AI自动生成失败:", e);
        // AI失败时仍创建空作业
      }
    }

    // 普通创建（无自动生成）
    const quiz = await prisma.quizActivity.create({
      data: {
        subProjectId,
        title,
        description: description || null,
        quizDesignTemplateId: defaultTemplate?.id || null,
        passScore: passScore || 60,
        status: "INACTIVE",
        analysisPrompt: analysisPrompt || null,
        updatedAt: new Date(),
      },
      include: { Question: { orderBy: { order: "asc" } } },
    });
    const { Question: Q4, ...quizData4 } = quiz;
    return NextResponse.json({ ...quizData4, questions: Q4, autoGenerated: false, count: 0 }, { status: 201 });
  } catch (error) {
    console.error("创建课堂作业失败:", error);
    return new Response("创建失败", { status: 500 });
  }
}

export async function GET(req: NextRequest) {
  try {
    const token = req.headers.get("authorization")?.replace("Bearer ", "");
    if (!token) return new Response("未登录", { status: 401 });
    const payload = await verifyToken(token);
    if (!payload) return new Response("登录已过期", { status: 401 });

    const { searchParams } = new URL(req.url);
    const subProjectId = searchParams.get("subProjectId");

    const where: Record<string, unknown> = {
      SubProject: { task: { teacherId: String(payload.userId) } },
    };
    if (subProjectId) where.subProjectId = subProjectId;

    const quizzes = await prisma.quizActivity.findMany({
      where,
      include: {
        SubProject: { select: { id: true, title: true, task: { select: { id: true, title: true } } } },
        Question: { orderBy: { order: "asc" } },
        _count: { select: { QuizAttempt: true } },
      },
      // 排序：生效中(ACTIVE) > 失效中(INACTIVE) > 草稿(INACTIVE)
      orderBy: [
        { status: "asc" }, // ACTIVE在前，INACTIVE在后
        { sortOrder: "asc" },
        { updatedAt: "desc" },
      ],
    });

    // 查询所有作业的 AI 分析报告
    const quizIds = quizzes.map((q) => q.id);
    const insights = await prisma.aIInsight.findMany({
      where: { type: "quiz_class", scopeId: { in: quizIds } },
      orderBy: { version: "desc" },
    });
    // 去重：每个 quiz 只留最新版本
    const latestInsightMap = new Map<string | null, typeof insights[0]>();
    for (const ins of insights) {
      if (!latestInsightMap.has(ins.scopeId)) latestInsightMap.set(ins.scopeId, ins);
    }

    const quizzesWithInsights = quizzes.map((q) => {
      const ins = latestInsightMap.get(q.id);
      const { SubProject, Question, _count, ...rest } = q;
      return {
        ...rest,
        subProject: SubProject,
        questions: Question,
        _count: { attempts: _count.QuizAttempt },
        hasAIAnalysis: !!ins,
        aiAnalysisVersion: ins?.version || null,
      };
    });

    return NextResponse.json(quizzesWithInsights);
  } catch (error) {
    console.error("查询课堂作业失败:", error);
    return new Response("查询失败", { status: 500 });
  }
}
