"use client";
import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { Switch, MessagePlugin } from "tdesign-react";

export default function TeacherQuizListPage() {
  const params = useParams();
  const router = useRouter();
  const subProjectId = params.subProjectId as string;

  const [quizzes, setQuizzes] = useState<any[]>([]);
  const [showModal, setShowModal] = useState(false);
  const [newTitle, setNewTitle] = useState("");
  const [newDesc, setNewDesc] = useState("");
  const [newPassScore, setNewPassScore] = useState(60);
  const [autoGenerate, setAutoGenerate] = useState(true);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [togglingId, setTogglingId] = useState<string | null>(null);

  useEffect(() => {
    const token = localStorage.getItem("token");
    if (!token) { router.push("/login"); return; }
    fetch(`/api/quiz-activities?subProjectId=${subProjectId}`, {
      headers: { Authorization: `Bearer ${token}` },
    })
      .then((r) => r.json())
      .then((data) => { setQuizzes(Array.isArray(data) ? data : []); setLoading(false); })
      .catch(console.error);
  }, [subProjectId, router]);

  const handleCreate = async () => {
    if (!newTitle.trim()) return;
    setCreating(true);
    const token = localStorage.getItem("token") || "";
    const res = await fetch("/api/quiz-activities", {
      method: "POST",
      headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
      body: JSON.stringify({ subProjectId, title: newTitle, description: newDesc, autoGenerate, passScore: newPassScore }),
    });
    const data = await res.json();
    if (res.ok) {
      if (data.autoGenerated) {
        MessagePlugin.success(`作业已创建并自动生成 ${data.count} 道题目`);
      } else {
        setQuizzes((prev) => [data, ...prev]);
        MessagePlugin.success("作业已创建");
      }
      setShowModal(false);
      setNewTitle("");
      setNewDesc("");
      setNewPassScore(60);
      router.push(`/teacher/activities/${subProjectId}/quiz/${data.id}`);
    } else {
      MessagePlugin.error(data.error || "创建失败");
    }
    setCreating(false);
  };

  // 切换生效/失效状态
  const handleToggle = async (quiz: any, checked: boolean) => {
    setTogglingId(quiz.id);
    try {
      const token = localStorage.getItem("token") || "";
      const res = await fetch(`/api/quiz-activities/${quiz.id}/enabled`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` },
        body: JSON.stringify({ enabled: checked }),
      });
      if (res.ok) {
        setQuizzes((prev) =>
          prev.map((q) => (q.id === quiz.id ? { ...q, status: checked ? "ACTIVE" : "INACTIVE" } : q))
        );
        MessagePlugin.success(checked ? "作业已生效" : "作业已失效");
      } else {
        const err = await res.json().catch(() => ({ error: "切换失败" }));
        MessagePlugin.error(err.error || "切换失败");
      }
    } catch (e) {
      MessagePlugin.error("切换失败");
    } finally {
      setTogglingId(null);
    }
  };

  // 获取状态显示（二态）
  const getStatusLabel = (q: any) => {
    if (q.status === "ACTIVE") return "生效中";
    return "失效中";
  };

  // 获取状态颜色（二态）
  const getStatusColor = (q: any) => {
    if (q.status === "ACTIVE") return "bg-green-100 text-green-700";
    return "bg-orange-100 text-orange-700";
  };

  if (loading) return <div className="p-6 text-center">加载中...</div>;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-xl font-semibold text-gray-800">课堂作业</h1>
          <div className="text-sm text-gray-400">管理作业题目和发布</div>
        </div>
        <button
          onClick={() => setShowModal(true)}
          className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm"
        >
          + 新建作业
        </button>
      </div>

      {quizzes.length === 0 ? (
        <div className="text-center py-12 text-gray-400 bg-white rounded-xl">
          暂无作业，点击上方"新建作业"创建
        </div>
      ) : (
        <div className="space-y-3">
          {quizzes.map((q) => (
            <div key={q.id} className="bg-white rounded-xl shadow-sm p-4 flex items-center gap-4">
              {/* 状态标签 */}
              <div className="flex items-center gap-2">
                <span className={`px-2 py-0.5 rounded-full text-xs ${getStatusColor(q)}`}>
                  {getStatusLabel(q)}
                </span>
              </div>

              {/* 作业信息 */}
              <div
                className="flex-1 cursor-pointer"
                onClick={() => router.push(`/teacher/activities/${subProjectId}/quiz/${q.id}`)}
              >
                <div className="font-medium text-gray-800">{q.title}</div>
                <div className="text-sm text-gray-400">{q.description || "无说明"} · {q.questions?.length || 0}题 · {q._count?.attempts || 0}人已答</div>
              </div>

              {/* 开关 */}
              <div className="flex items-center gap-3">
                <Switch
                  value={q.status === "ACTIVE"}
                  onChange={(val: boolean) => handleToggle(q, val)}
                  disabled={togglingId === q.id}
                />

                <button
                  onClick={(e) => { e.stopPropagation(); router.push(q.status === "ACTIVE" ? `/teacher/activities/${subProjectId}/quiz/${q.id}/report` : `/teacher/activities/${subProjectId}/quiz/${q.id}/questions`); }}
                  className="px-3 py-1.5 text-sm text-blue-600 border border-blue-300 rounded-lg hover:bg-blue-50"
                >
                  {q.status === "ACTIVE" ? "查看报告" : "题目管理"}
                </button>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* 新建弹窗 */}
      {showModal && (
        <div className="fixed inset-0 bg-black/30 flex items-center justify-center z-50">
          <div className="bg-white rounded-xl p-6 w-96 shadow-xl">
            <h2 className="text-lg font-semibold mb-4">新建作业</h2>
            <input
              className="w-full border rounded-lg px-3 py-2 mb-3 text-sm"
              placeholder="作业名称"
              value={newTitle}
              onChange={(e) => setNewTitle(e.target.value)}
              autoFocus
            />
            <textarea
              className="w-full border rounded-lg px-3 py-2 mb-3 text-sm"
              placeholder="作业说明（选填）"
              value={newDesc}
              onChange={(e) => setNewDesc(e.target.value)}
              rows={3}
            />
            <div className="flex items-center gap-3 mb-4">
              <label className="text-sm text-gray-600">合格线分值</label>
              <input
                type="number"
                min={0}
                max={100}
                className="w-20 border rounded-lg px-3 py-2 text-sm text-center"
                value={newPassScore}
                onChange={(e) => setNewPassScore(Number(e.target.value) || 60)}
              />
              <span className="text-xs text-gray-400">默认60分</span>
            </div>
            <div className="flex gap-3 justify-end">
              <button onClick={() => setShowModal(false)} className="px-4 py-2 text-gray-500 text-sm">取消</button>
              <button onClick={handleCreate} disabled={creating || !newTitle.trim()} className="px-4 py-2 bg-blue-600 text-white rounded-lg text-sm disabled:opacity-50">
                {creating ? "创建中..." : "创建"}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
